modLoader="javafml" #mandatory
loaderVersion="${forge_version_range}"
license="MIT License"
[[mods]] #mandatory
updateJSONURL = "https://raw.githubusercontent.com/Kapitencraft/Mysticcraft/master/mysticcraft-version.json"
modId="${mod_id}" #mandatory
version="0.9.9e" #mandatory
displayName="${mod_name}" #mandatory
logoFile="examplemod.png" #optional
credits="" #optional
authors="Kapitencraft: Dev; Beefrient, WarpBeat(, Lenori): Textures"
description='''
CREDITS:
    Some Textures mad by the author(s) of Necron's Pack Hypixel Skyblock
    some Textures made by Beefrient
    some Textures made by Jendrikose08
    heart of the nether texture made by Lenori


A very magical mod
'''
[[dependencies.mysticcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mysticcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"