modLoader="javafml" #mandatory
updateJSONURL = ""
loaderVersion="[42,)"
license="MIT License"
[[mods]] #mandatory
modId="mysticcraft" #mandatory
version="0.4.9-1.19.3" #mandatory
displayName="Mysticcraft" #mandatory
logoFile="examplemod.png" #optional
credits="" #optional
authors="Kapitencraft: Dev; Lenori, Beefrient: Textures; Lenori: Testing" #optional
description='''
CREDITS:
    Some Textures mad by the author(s) of Necron's Pack Hypixel Skyblock
    Textures for the elements made by Kraft007
    some Textures made by Beefrient
    some Textures made by Jendrikose08
    heart of the nether texture made by Lenori


A very magical mod
'''
[[dependencies.mysticcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[42,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mysticcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"