modLoader="javafml" #mandatory
loaderVersion="${forge_version_range}"
license="MIT License"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="1.0-pre1" #mandatory
issueTrackerURL="https://discord.gg/ByxUBgPB"
displayName="${mod_name}" #mandatory
logoFile="examplemod.png" #optional
credits='''
    Some Textures mad by the author(s) of Necron's Pack Hypixel Skyblock
    most Textures made by Beefrient
    some Textures made by Jendrikose08
    heart of the nether texture made by Lenori
''' #optional
authors="Kapitencraft: Dev; Beefrient, WarpBeat(, Lenori): Textures"
description='''
A very magical mod
'''
[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"