modLoader="javafml" #mandatory
loaderVersion="${forge_version_range}"
license="MIT License"
[[mods]] #mandatory
updateJSONURL = "https://raw.githubusercontent.com/Kapitencraft/Mysticcraft/master/mysticcraft-version.json"
modId="mysticcraft" #mandatory
version="1.0-pre1" #mandatory
issueTrackerURL="https://discord.gg/ByxUBgPB"
displayName="Mysticcraft" #mandatory
logoFile="examplemod.png" #optional
credits='''
    Some Textures mad by the author(s) of Necron's Pack Hypixel Skyblock
    most Textures made by Beefrient
    some Textures made by Jendrikose08
    heart of the nether texture made by Lenori
''' #optional
authors="Kapitencraft: Dev; Beefrient, WarpBeat(, Lenori): Textures"
description='''
A very magical mod
'''
[[dependencies.mysticcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[42,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mysticcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"